# Title of the document
title: "AllSpark Profiling Report"

# Number of workers (0=multiprocessing.cpu_count())
pool_size: 0

# Per variable type description settings
vars:
    num:
          quantiles:
                - 0.05
                - 0.25
                - 0.5
                - 0.75
                - 0.95
          skewness_threshold: 20
    cat:
        check_composition: True
# Sort the variables. Possible values: ascending, descending or None (leaves original sorting)
sort: ascending

low_categorical_threshold: 5

# Settings regarding warnings
cardinality_threshold: 50

# For numeric
check_correlation_pearson: True
correlation_threshold_pearson: 0.9

# For categorical
check_correlation_cramers: False
correlation_threshold_cramers: 0.9
categorical_maximum_correlation_distinct: 100

# These variables are not rejected in the correlation checks
correlation_overrides: []
check_recoded: True

# The number of observations to show
n_obs_unique: 5
n_obs_bool: 3
n_extreme_obs: 5
n_freq_table_max: 10

# When in a Jupyter notebook
notebook:
    iframe:
        height: '800px'
        width: '100%'
        attribute: 'srcdoc' # or 'src'
